### ISSUE TITLE
Roadmap to version 2.0

### ISSUE THREAD

**Issue by hanneskod** [hanneskod/yaysondb#2]
- [x] Require php 7.
- [x] Use generators all around.
- [x] Implement an `Engine` instead of defaulting to json content. The datasource could be anything (eg a line based textfile, csv, an array, a json string, or whatever...). Some engines may support a document id, others may not: Needs an abstract `Engine::accepts($data)` implementation instead of `Collection::containsDocument()`.
- [x] Make `Yaysondb` more versitile so that setup supports both `Adapter` and `Engine`. (Some engines might be auto-commit, others not. Some engines might be read-only, others not.. Needs a way to identify engine type in adapter. Maybe use Flysystem universally??)

Basic usage could be something like:

``` php
$db = new Yaysondb(
    // Could be a regular flysystem instance, or a MountManager if multiple
    // filesystems is to be used...
    new FlysystemSetup(...)
);

// creates local://log.txt if it does not exist
// chooses en Engine based on mime-type
$db->collection('local://log.txt')->insert('teststst')->commit();

// osv...
$db->collection('local://log.txt')->findOne(y::doc([
    '_id' => y::equals('1')
]));
```
